name: Cypress Smoke Tests

on:
  push:
  pull_request:

concurrency:
  group: cypress-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Limpar relatórios antigos
        run: npm run clean-report

      - name: Executar Smoke Tests
        run: npm run smoke

      - name: Gerar Merge do Mochawesome
        if: always()
        run: npm run merge-report

      - name: Gerar Relatório HTML
        if: always()
        run: npm run generate-report

      - name: Upload Relatório Mochawesome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome-Report
          path: cypress/reports

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: cypress/screenshots

      - name: Upload Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Videos
          path: cypress/videos